// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq26n_1HPwuAxra1loVHK_0BX_GyzPHYU',
    appId: '1:878941179468:web:53063a8ffa0c9300266ee9',
    messagingSenderId: '878941179468',
    projectId: 'notes-2fb86',
    authDomain: 'notes-2fb86.firebaseapp.com',
    storageBucket: 'notes-2fb86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb17XoODA-3JhSyTwvepWmq_Qfu3S6NYQ',
    appId: '1:878941179468:android:517425ce8c20fb69266ee9',
    messagingSenderId: '878941179468',
    projectId: 'notes-2fb86',
    storageBucket: 'notes-2fb86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD888bpCZktKrRhMYwKT8_4Qv3WjaMRDv0',
    appId: '1:878941179468:ios:dfc6539a68ab5a29266ee9',
    messagingSenderId: '878941179468',
    projectId: 'notes-2fb86',
    storageBucket: 'notes-2fb86.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD888bpCZktKrRhMYwKT8_4Qv3WjaMRDv0',
    appId: '1:878941179468:ios:dfc6539a68ab5a29266ee9',
    messagingSenderId: '878941179468',
    projectId: 'notes-2fb86',
    storageBucket: 'notes-2fb86.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq26n_1HPwuAxra1loVHK_0BX_GyzPHYU',
    appId: '1:878941179468:web:2cecd9fbddca9e87266ee9',
    messagingSenderId: '878941179468',
    projectId: 'notes-2fb86',
    authDomain: 'notes-2fb86.firebaseapp.com',
    storageBucket: 'notes-2fb86.firebasestorage.app',
  );
}
