// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh24mZFKQMxqmzItJx1gqyRiiVy8K7WOk',
    appId: '1:217575250466:web:59e119f1b534a1fa88887b',
    messagingSenderId: '217575250466',
    projectId: 'daftarbelanja-9fea5',
    authDomain: 'daftarbelanja-9fea5.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-9fea5-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-9fea5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDubaxG0uLAeqr3Y3-mWkZeOMy8uEum98',
    appId: '1:217575250466:android:890395c1797fb24388887b',
    messagingSenderId: '217575250466',
    projectId: 'daftarbelanja-9fea5',
    databaseURL: 'https://daftarbelanja-9fea5-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-9fea5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcSNWyF6alwD8FUDW22xrPj0WMNpeGWvc',
    appId: '1:217575250466:ios:875b6a897c60e3ee88887b',
    messagingSenderId: '217575250466',
    projectId: 'daftarbelanja-9fea5',
    databaseURL: 'https://daftarbelanja-9fea5-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-9fea5.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcSNWyF6alwD8FUDW22xrPj0WMNpeGWvc',
    appId: '1:217575250466:ios:875b6a897c60e3ee88887b',
    messagingSenderId: '217575250466',
    projectId: 'daftarbelanja-9fea5',
    databaseURL: 'https://daftarbelanja-9fea5-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-9fea5.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh24mZFKQMxqmzItJx1gqyRiiVy8K7WOk',
    appId: '1:217575250466:web:30d90b5798a8fc2b88887b',
    messagingSenderId: '217575250466',
    projectId: 'daftarbelanja-9fea5',
    authDomain: 'daftarbelanja-9fea5.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-9fea5-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-9fea5.firebasestorage.app',
  );

}